Add Update Sub-command to Issue Command
profclems/glab pull request #240
Opened 2020-10-02 03:11 UTC by sunzoje

This PR will add `update` sub-command to `issue` command.
`update` sub-command edits gitlab issue.
Currently supported flags are:
* --label: add labels takes comma separated values
* --unlabel: remove labels takes comma separated values
* --title: update title of the issue
* --description: update descriptions of the issue
* --lock-discussion: lock comments takes boolean value

**Related Issue**
Addresses Issue #230 

**Types of changes**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-02 04:53 UTC, profclems requested changes
I would appreciate a test by mocking. 
See https://github.com/profclems/glab/blob/trunk/commands/issue/close/issue_close_test.go

Great work overall🎉

2020-10-02 04:53 UTC, profclems commented on commands/issue/issue.go
> +  issueUpdateCmd "github.com/profclems/glab/commands/issue/update"
Looks like it's not been gofmted. Must align with the other imports

2020-10-02 05:29 UTC, sunzoje commented
> I would appreciate a test by mocking.
> See https://github.com/profclems/glab/blob/trunk/commands/issue/close/issue_close_test.go
> 
> Gre

> I would appreciate a test by mocking.
> See https://github.com/profclems/glab/blob/trunk/commands/issue/close/issue_close_test.go
> 
> Great work overall🎉

Thanks. Will check it out.

2020-10-02 13:31 UTC, profclems commented
I'm currently fixing the issue with travis ci test. I passed a GITLAB_TOKEN as a secure variable but it doesn't work on forks. Travis does not use it on PRs from forks so I'm reverting the tests to using mocks

2020-10-03 07:40 UTC, profclems approved these changes

2020-10-03 22:25 UTC, merged