Hostname validator
profclems/glab pull request #518
Opened 2021-01-05 21:29 UTC by maxice8

**Description**

make `hostnameValidator()`  more robust

**How Has This Been Tested?**

Tests

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

2021-01-05 23:39 UTC, profclems requested changes

2021-01-05 23:39 UTC, profclems commented on commands/auth/login/login.go
> +	re := regexp.MustCompile("^[A-Za-z0-9][A-Za-z0-9-\\.]*$")
> should use raw string (\`...\`) with regexp.MustCompile to avoid having to escape twice (gosimple)

Also the escape sequence `\.` is redundant

```suggestion
	re := regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9-.]*$`)
```

2021-01-05 23:43 UTC, profclems commented
I'm happy we are gradually adding more tests to improve our test coverage 🎉

2021-01-05 23:44 UTC, maxice8 commented
Thanks for the review I'll fix it soon, working on another part of the project.

2021-01-06 01:43 UTC, profclems approved these changes

2021-01-06 01:46 UTC, profclems commented
Since this enhances the hostname validator, I'm adding it to the [GLab](https://github.com/profclems/glab/projects/1) project so it will be added to the release note

2021-01-06 13:50 UTC, merged