add EXAMPLES for subcommands of `issue` subcommand
profclems/glab pull request #541
Opened 2021-01-08 20:43 UTC by maxice8

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

2021-01-08 22:08 UTC, profclems commented on commands/issue/unsubscribe/issue_unsubscribe.go
> +			$ glab unsub 123
```suggestion
			$ glab issue unsubscribe 123
			$ glab issue unsub 123
```

2021-01-08 22:09 UTC, profclems requested changes

2021-01-08 22:09 UTC, profclems commented on commands/issue/reopen/issue_reopen.go
> +			$ glab open 123
```suggestion
			$ glab issue reopen 123
			$ glab issue open 123
```

2021-01-08 22:11 UTC, profclems commented on commands/issue/subscribe/issue_subscribe.go
> +			$ glab sub 123
```suggestion
			$ glab subscribe 123
			$ glab sub 123
```

2021-01-09 01:57 UTC, profclems approved these changes

2021-01-09 02:35 UTC, maxice8 commented
Should this wait and be adapted for #546 ?

2021-01-09 02:54 UTC, profclems commented
Yeah... We'd have to add examples specifying URLs as args.

2021-01-10 01:39 UTC, profclems commented
This can now be adapted for #546

2021-01-10 01:40 UTC, maxice8 commented
Thanks, I'll adapt tomorrow, tonight is :video_game: night.

2021-01-10 18:41 UTC, maxice8 commented
rebased and wrote examples with URLs, can you check ?

2021-01-11 11:40 UTC, merged