added push mirror and command
profclems/glab pull request #887
Opened 2021-10-23 09:47 UTC by NikhilMJagtap

feat adding command for push and pull mirrors of repository

commits:
- added command for mirror
- added push mirror
- added pull mirror

2021-10-24 06:12 UTC, profclems requested changes
This is great @NikhilMJagtap!

2021-10-24 06:12 UTC, profclems commented on commands/project/mirror/project_mirror.go
> +		Long:  `Mirrors a project/repository to the specified location using speicified method.`,
Typo in ~speicified~ specified method.

Or maybe we can say: `Mirrors a project/repository to the specified location using pull or push method.` ?

2021-10-24 06:12 UTC, profclems commented on api/mirror.go
> +var CreatePullMirror = func(
You can enable pull mirroring using the Edit Project API https://docs.gitlab.com/ee/api/projects.html#edit-project which should be available in `go-gitlab`.

2021-10-24 06:12 UTC, profclems commented on commands/project/mirror/project_mirror.go
> +		Args:  cobra.MaximumNArgs(1),
Why not `cobra.ExactArgs(1)` ? Also, if we are using cobra.MaximumNArgs(1), then we should allow no argument at all and use the current local git repo from which the command is executed.

2021-10-24 06:37 UTC, NikhilMJagtap commented on commands/project/mirror/project_mirror.go
> +		Args:  cobra.MaximumNArgs(1),
`ExactArgs` is better option, I agree.

2021-10-24 06:37 UTC, NikhilMJagtap commented on commands/project/mirror/project_mirror.go
> +		Long:  `Mirrors a project/repository to the specified location using speicified method.`,
Noted. Thanks.

2021-10-24 07:52 UTC, profclems requested changes

2021-10-24 07:52 UTC, profclems commented on api/mirror.go
> +	keepDivergentRefs bool,
we can have these as separate type struct options for CreatePushMirror
```go
type CreatePushMirrorOptions struct {
    url string
    enabled bool
    onlyProtectedBranches bool
    keepDivergentRefs bool
}
```
And the function signature becomes: 
```go
var CreatePushMirror = func(client *gitlab.Client, projectID interface{}, opts *CreatePushMirrorOptions) (*gitlab.ProjectMirror, error)
```

2021-10-24 07:52 UTC, profclems commented on api/mirror.go
> +	onlyProtectedBranches bool,
Same as above ^^

2021-10-24 07:52 UTC, profclems commented on commands/project/mirror/project_mirror.go
> +	projectMirrorCmd.Flags().BoolVar(&opts.AllowDivergence, "allow-divergence", false, "Determines if divergent refs are skipped.")
We should check that the user does not use `--direction pull` and `--allow-divergence` together, since the `--allow-divergence` is useless for pull mirroring.

2021-10-24 07:52 UTC, profclems commented on commands/project/mirror/project_mirror.go
> +			}
We may have to reword this error message. `url` is a flag, not an argument.

Or the easiest thing to do is mark the flag as required with so you don't have to manually validate.

Here is an example: https://github.com/profclems/glab/blob/045610825ba1362f80524f7be3ccb47d059d4a09/commands/ssh-key/add/add.go#L69-L74

2021-10-24 07:52 UTC, profclems commented on commands/project/mirror/project_mirror.go
> +	projectMirrorCmd.Flags().StringVar(&opts.Direction, "direction", "pull", "Mirror direction")
Should we avoid the default and mark this flag too as required?

2021-10-27 09:47 UTC, profclems approved these changes
Looks great! Thanks for working on this @NikhilMJagtap.

Note that I will be adding a few commits to allow for full gitlab project url instead of just `project/repository`

2021-11-27 15:00 UTC, NikhilMJagtap commented
@profclems 
Any update on this? Getting marked stale so pinging you once. Please ignore if expected or normal. Thanks.

2021-12-20 17:37 UTC, merged