feature: add variable delete command
profclems/glab pull request #890
Opened 2021-10-26 05:30 UTC by bradym

## Description
This PR addresses #889 by adding a new `glab variable delete` command. 

I tried to follow established patterns as best I could, but please let me know what improvements you'd like to see. 

In addition to adding the delete command, I added a new `variableutils` package and moved the `isValidKey` function and `validKeyMsg` there so they could be shared between the `set` and `delete` commands.

I have marked this as a draft PR as I have not yet added tests for the new delete command code, I will work on that this week. I wanted to get this PR created to get any feedback you may have so I can address that while working on the tests.

## How Has This Been Tested?
So far I have tested by running the commands in the help output:

```
  $ glab variable delete VAR_NAME
  $ glab variable delete VAR_NAME --scope=prod
  $ glab variable delete VARNAME -g mygroup
```

I've also run existing tests to ensure my changes have not broken any existing functionality related to variables:

```
root@dd3ab0757245:/app# bin/gotestsum --packages ./commands/variable
✓  commands/variable (17ms)

DONE 1 tests in 0.971s

root@dd3ab0757245:/app# bin/gotestsum --packages ./commands/variable/set
✓  commands/variable/set (19ms)

DONE 14 tests in 1.026s

root@dd3ab0757245:/app# bin/gotestsum --packages ./commands/variable/variableutils
✓  commands/variable/variableutils (cached)

DONE 4 tests in 0.223s
```
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

2021-10-26 07:14 UTC, profclems requested changes
This is a great work! Thanks for working on this @bradym

2021-10-26 07:15 UTC, profclems commented on commands/variable/delete/delete.go
> +		Aliases: []string{"delete", "remove"},
No need to add `delete` again to the aliases.

2021-10-28 04:55 UTC, bradym commented
I've just pushed my first attempt at tests, I've got one working and one failing at the moment. I'm a bit stuck and could use some help getting the broken test to work.

@profclems any hints you can give me on using RegisterResponder correctly? For quick reference, here's what I've got:

```
	reg := &httpmock.Mocker{
		MatchURL: httpmock.PathAndQuerystring,
	}
	defer reg.Verify(t)

	reg.RegisterResponder("DELETE", "projects/owner%2Frepo/variables/TEST_VAR?filter%5Benvironment_scope%5D=%2A",
		httpmock.NewStringResponse(204, ""),
	)
```
I've tried different combinations of urlencoding and not urlencoding the various characters in the URL, but I've not come across a successful combination yet.

Here's what I'm currently getting when with the test fails:

```
$ go test -timeout 30s -run ^Test_deleteRun_project$ github.com/profclems/glab/commands/variable/delete
--- FAIL: Test_deleteRun_project (0.00s)
        Error Trace:    assertions.go:85
        		assertions.go:191
        		assertions.go:744
        		delete_test.go:117
        Error:		No error is expected but got Delete "https://gitlab.com/api/v4/projects/owner%2Frepo/variables/TEST_VAR?filter%5Benvironment_scope%5D=%2A": no registered stubs matched &{DELETE https://gitlab.com/api/v4/projects/owner%2Frepo/variables/TEST_VAR?filter%5Benvironment_scope%5D=%2A HTTP/1.1 1 1 map[Accept:[application/json] Private-Token:[] User-Agent:[GLab - GitLab CLI]] <nil> <nil> 0 [] false gitlab.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc0000b6010}
        
    panic.go:617: 1 unmatched HTTP stubs
FAIL
FAIL	github.com/profclems/glab/commands/variable/delete	0.013s
FAIL
```

2021-10-29 03:20 UTC, bradym commented
Figured out the tests, please let me know if you see any issues.

2021-11-03 16:25 UTC, profclems approved these changes
LGTM!

Thanks so much for working on this

2021-11-03 16:26 UTC, merged