Documentation alert
profclems/glab pull request #894
Opened 2021-11-02 11:42 UTC by braswelljr

## Description
Alert for New Documentation at [https://glab-cli.io](https://glab-cli.io)

## Related Issue

Resolves #[issue_number]

## How Has This Been Tested?

## Screenshots (if appropriate)
![Screenshot from 2021-11-02 11-38-54](https://user-images.githubusercontent.com/53278231/139839584-b0cd2fb5-4666-4af0-9c85-79f9b5ecce00.png)
![Screenshot from 2021-11-02 11-40-46](https://user-images.githubusercontent.com/53278231/139839826-9f097272-06fd-4ba7-bf35-025717861516.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

2021-11-03 16:21 UTC, profclems requested changes
Great work @braswelljr! 

Thanks so much for working on this. We may have to decide whether to move the docs from the https://github.com/braswelljr/glab-docs repo to the /docs folder in this repo or maintain it at the current repo.

2021-11-03 16:21 UTC, profclems commented on README.md
> +Download a binary suitable for your OS at the [releases page](https://github.com/profclems/glab/releases/latest)
We want to maintain the period at the end.

2021-11-03 16:21 UTC, profclems commented on README.md
> +Get the new documentation on [`https://glab-cli.io`](https://glab-cli.io) and contribute to the new documentation on [https://github.com/braswelljr/glab-docs](https://github.com/braswelljr/glab-docs)
Remove the documentation header. 

I'm thinking maybe we could move the docs from the https://github.com/braswelljr/glab-docs repo to the /docs folder in this repo.

2021-11-04 14:47 UTC, braswelljr commented
I am glad my work has been approved.

I am ready to do what is best and help improve and make sure we deliver a
good and user friendly service to the open source community.

Yours faithfully,

Braswell Kenneth Azu Junior
+233500181106

On Thu, 4 Nov 2021, 2:33 pm codecov[bot], ***@***.***> wrote:

> Codecov
> <https://codecov.io/gh/profclems/glab/pull/894?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Clement+Sam>
> Report
>
> Merging #894
> <https://codecov.io/gh/profclems/glab/pull/894?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Clement+Sam>
> (a684bfa
> <https://github.com/profclems/glab/commit/a684bfa53a1da46166705ef848e833e0d9641e2d>)
> into docs-markdown
> <https://codecov.io/gh/profclems/glab/commit/88df561ca57b6f7f9b45f28cfffed6d95c4dcb3c?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Clement+Sam>
> (88df561
> <https://github.com/profclems/glab/commit/88df561ca57b6f7f9b45f28cfffed6d95c4dcb3c>)
> will *not change* coverage.
> The diff coverage is n/a.
>
> [image: Impacted file tree graph]
> <https://codecov.io/gh/profclems/glab/pull/894?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Clement+Sam>
>
> @@              Coverage Diff               @@
> ##           docs-markdown     #894   +/-   ##
>
> ==============================================
>
>   Coverage          59.41%   59.41%
>
> ==============================================
>
>   Files                 93       93
>
>   Lines               7341     7341
>
> ==============================================
>
>   Hits                4362     4362
>
>   Misses              2599     2599
>
>   Partials             380      380
>
> ------------------------------
>
> Continue to review full report at Codecov
> <https://codecov.io/gh/profclems/glab/pull/894?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Clement+Sam>
> .
>
> *Legend* - Click here to learn more
> <https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Clement+Sam>
> Δ = absolute <relative> (impact), ø = not affected, ? = missing data
> Powered by Codecov
> <https://codecov.io/gh/profclems/glab/pull/894?src=pr&el=footer&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Clement+Sam>.
> Last update 88df561...a684bfa
> <https://codecov.io/gh/profclems/glab/pull/894?src=pr&el=lastupdated&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Clement+Sam>.
> Read the comment docs
> <https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Clement+Sam>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/profclems/glab/pull/894#issuecomment-961062462>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMWPMFZDVHUY5WI7WKVKOA3UKKKSPANCNFSM5HGH4DMA>
> .
>

2023-01-13 17:16 UTC, closed without merging