feature: Read config directory from GLAB_CONFIG_DIR
profclems/glab pull request #921
Opened 2021-11-28 16:21 UTC by kampka

## Description

When working with many different gitlab instances for different
projects, the global config quickly gets cluttered up with
specific settings that do not clean up conveniently. On the other hand,
local configs are to local, restricting the config to one repository
instead of one project or instance that potentially contains many
relevant repositories.
This change introduces a middle ground solution via the GLAB_CONFIG_DIR
environment variable. Setting this variable will allow global
configuration to travel with the project instead of populating the XDG
global config.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

2021-11-29 06:38 UTC, zemzale requested changes
I actually like this change. There should be some changes to documentation so users know about this.

Also would need approval from @profclems but this LGTM!

2021-11-29 14:29 UTC, kampka commented
> There should be some changes to documentation so users know about this.

Agreed. I added a comment to the README as I could not find any mentioning of the config files in the documentation at all.

2021-12-02 13:52 UTC, profclems requested changes
This is great!

Please add it to the env vars here https://github.com/profclems/glab/blob/9b44934c07d1a17d19fd26d5886a752d7cf06a30/commands/root.go#L41-L60

2021-12-02 14:18 UTC, kampka commented
Done.

2021-12-02 16:48 UTC, profclems approved these changes

2021-12-02 16:49 UTC, merged