fix: Don't show non-templates when asking chosing
profclems/glab pull request #927
Opened 2021-12-14 16:12 UTC by zemzale

## Description

In cases where users have non template files in the .gitlab/[template]/
folder they might will be picked up and displayed.

This fixes that by filtering out all the files that are hidden and don't
end in .md

## Related Issue

Resolves #923

## How Has This Been Tested?

Unit tests

## Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

2021-12-14 16:14 UTC, zemzale commented
I don't know if this is the correct way how to setup testing for this, but it works 😄

2022-01-19 01:29 UTC, profclems requested changes
This looks good but I'm only concerned about the new test files in the main issue templates folder.

Maybe we could move them to `test/testdata/.gitlab` ?

2022-01-20 12:34 UTC, zemzale commented
I moved the test files to the testdata directory. 

I had to override the git function for getting top-level directory, but this should be fine as long as we don't allow overriding this outside the tests.

2022-01-25 08:23 UTC, profclems commented
> I moved the test files to the testdata directory.
> 
> I had to override the git function for getting top-level directory, but this should be fine as long as we don't allow overriding this outside the tests.

Sounds good.

2022-01-25 08:25 UTC, profclems requested changes
One last fix for the tests

2022-01-25 08:25 UTC, profclems commented on commands/cmdutils/cmdutils_test.go
> +			wantTemplates: []string{"Feature Request", "Bug"},
I think it should be `[]string{"Bug", "Feature Request"}` instead.

2022-01-31 18:03 UTC, zemzale commented on commands/cmdutils/cmdutils_test.go
> +			wantTemplates: []string{"Feature Request", "Bug"},
So they show up in alphabetic order? I am just gonna sort the list before returning it.

2022-01-31 18:05 UTC, profclems approved these changes

2022-01-31 18:20 UTC, merged