Change flag which causes errors in some shells
profclems/glab pull request #951
Opened 2022-02-09 10:29 UTC by byteknacker

## Description

When installing glab on alpine 3.14 based Docker images, the following script throws a grep unexpected option error for the --only flag. Upon inspection of grep --help, --only does not exist. Use -o or --only-matching instead to have the same result. 

The installation command used here is:

curl -sL https://j.mp/glab-cli | sudo sh

## How Has This Been Tested?

I used this in my own Docker image based on the FROM python:3.7.12-alpine3.14 and it successfully installed version 1.22, i.e. the currently latest version of glab. 

## Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

2022-02-09 11:08 UTC, zemzale commented on scripts/install.sh
> +latest="$(curl -sL 'https://api.github.com/repos/profclems/glab/releases/latest' | grep 'tag_name' | grep -o 'v[0-9\.]\+' | cut -c 2-)"
Could maybe change this to the `--only-matching`, since in scripts it's better to have the full names, since it' s easier to read and understand it

2022-02-09 11:09 UTC, zemzale requested changes
Thanks for the PR. I have only one small change I would like to see.

2022-02-16 16:17 UTC, byteknacker commented
> Thanks for the PR. I have only one small change I would like to see.

Just made the change to the verbose flag. Does that look good?

2022-02-16 22:07 UTC, zemzale approved these changes
LGTM

2022-02-16 22:07 UTC, merged

2022-03-03 14:22 UTC, byteknacker commented
Ok, I just found out that for me at least, this --only-matching causes errors. The grep in the base docker image I am using does not recognise this flag, only -o is recognised. Cannot show details since it is for my client.  I just want to point out that for some -o is better than --only-matching.