fix: copypasta errors for `glab issue view --help`
profclems/glab pull request #973
Opened 2022-03-10 04:47 UTC by justin-f-perez

Fix `glab issue view --help` descriptions in `FLAGS` section for `--comments` and `--web` (mr -> issue)

## Description
Fix `glab issue view --help` descriptions in `FLAGS` section for `--comments` and `--web` (mr -> issue)

## Related Issue

Resolves #972

## How Has This Been Tested?

Not tested (simple string change)

## Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

2022-03-10 04:55 UTC, justin-f-perez commented
Oops... just noticed there's some documentation to update as well. will amend commit and push

2022-03-10 06:15 UTC, zemzale requested changes
Thanks for the PR @justin-f-perez. One small thing about the docs, otherwise LGTM

2022-03-10 06:15 UTC, zemzale commented on docs/source/issue/view.rst
> +  -c, --comments       Show issue comments and activities
No need to change the docs here. They are generated automatically when creating a release using the `make gen-docs` command.

2022-03-10 15:20 UTC, justin-f-perez commented on docs/source/issue/view.rst
> +  -c, --comments       Show issue comments and activities
should be resolved now, thanks for noting it!

2022-03-11 06:11 UTC, zemzale approved these changes

2022-03-11 06:17 UTC, merged